version: "3.3"

services:
  tester:
    image: ${DOCKER_IMG}
    container_name: aaqua_tester
    command: pytest /service/src/ ${PYTEST_OPT}
    environment:
      SERVER_HOST_NAME: server
      DB_HOST_NAME: database
      DB_PORT: ${DB_PORT}
      GRPC_PORT: ${GRPC_PORT}
      REST_PORT: ${REST_PORT}
    networks:
      - aaqua_net
    depends_on:
      - server
    profiles:
      - test

  server:
    image: ${DOCKER_IMG}
    container_name: aaqua_server
    command: python /service/src/main.py
    environment:
      GRPC_PORT: ${GRPC_PORT}
      REST_PORT: ${REST_PORT}
    volumes:
      - ./log:/service/src/log
    ports:
      - ${GRPC_PORT}:${GRPC_PORT}
      - ${REST_PORT}:${REST_PORT}
    networks:
      - aaqua_net
    depends_on:
      - database

  database:
    container_name: aaqua_db
    image: redis:6.2.6
    command: ["redis-server", "/redis.conf"]
    volumes:
      - ./redis/config/redis.conf:/redis.conf
      # Backup redis database to host machine
      - ./redis/data:/data
    networks:
      - aaqua_net

networks:
  aaqua_net:
